### ISSUE TITLE
User can search for a city, state, or zip

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/final-project#1]
## 💰 Motivation

To help people moving find a place to live.

## 📐 Plan

Create an app that allows users to search for a city, state, county, or zip.

## Mobile:
<img width="371" alt="Screen Shot 2021-04-06 at 11 55 38 AM" src="https://user-images.githubusercontent.com/52344883/113763946-277f8f80-96cf-11eb-9c4c-9a72d1207759.png">

## Desktop:
<img width="452" alt="Screen Shot 2021-04-06 at 11 58 30 AM" src="https://user-images.githubusercontent.com/52344883/113764150-70cfdf00-96cf-11eb-8d50-d0e701309bfa.png">
<img width="452" alt="Screen Shot 2021-04-06 at 11 58 36 AM" src="https://user-images.githubusercontent.com/52344883/113764154-7299a280-96cf-11eb-91d3-f1a5886c6331.png">

## ✅ Task List
- [x] Create header (with app name and menu dropdown)
- [x] Add background image to body container
- [x] Add floating body text, search and filter buttons, and a form with input type search
- [x] Listen for keydown events in the search bar
- [x] As the user types, send a GET request to find the cities, zipcodes with the closest resemblance to what the user has typed
- [x] Append the first 5 search results to the bottom of the search bar
- [x] Add appropriate CSS styling to get app to look like wireframe on both mobile and desktop
