### ISSUE TITLE
User can view search results

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/final-project#2]
## 💰 Motivation

Showing available properties to the user interested in moving.

## 📐 Plan

Load a page of search results in the form of images.

## Mobile
<img width="174" alt="Screen Shot 2021-04-06 at 12 01 17 PM" src="https://user-images.githubusercontent.com/52344883/113764460-d91ec080-96cf-11eb-8e34-dba24b2baf0c.png">

## Desktop
<img width="493" alt="Screen Shot 2021-04-06 at 12 01 29 PM" src="https://user-images.githubusercontent.com/52344883/113764473-dde37480-96cf-11eb-8f0d-af9656c19d75.png">

## ✅ Task List
- [x] Create a search-results.jsx file
- [x] Implement hash routing on home.jsx, search-results.jsx to tell app.jsx which file to render
- [x] Make the search suggestions export a class with state value set to the object of the div result that was clicked
- [x] Use the stored data to GET results from the zillow API
- [x] Render the results on the search results page
- [x] Use appropriate css styling to get app to look like wireframe
- [x] Make app dynamic on both mobile and desktop

**Comment by ameliatalkington** [comment]
<img width="995" alt="Screen Shot 2021-04-13 at 3 54 34 PM" src="https://user-images.githubusercontent.com/52344883/114631245-13103980-9c71-11eb-92c6-48192eff000f.png">
<img width="302" alt="Screen Shot 2021-04-13 at 3 54 41 PM" src="https://user-images.githubusercontent.com/52344883/114631250-160b2a00-9c71-11eb-83cf-508092ae6758.png">
<img width="844" alt="Screen Shot 2021-04-13 at 3 54 55 PM" src="https://user-images.githubusercontent.com/52344883/114631252-16a3c080-9c71-11eb-9d97-060c03632a89.png">
