### ISSUE TITLE
User can filter event results

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/final-project#3]
## 💰 Motivation

Help user filter results to find what they're looking for.

## 📐 Plan

Display a dropdown/page of filters to allow user to refine the search.

## Mobile
<img width="303" alt="Screen Shot 2021-04-19 at 9 21 07 AM" src="https://user-images.githubusercontent.com/52344883/115270636-5e06d280-a0f1-11eb-90c9-942e15bba079.png">

## Desktop
<img width="710" alt="Screen Shot 2021-04-19 at 9 21 13 AM" src="https://user-images.githubusercontent.com/52344883/115270627-5b0be200-a0f1-11eb-8b69-30c323d392cb.png">

## ✅ Task List
- [x] Create a form component when user clicks filter button on search results
- [x] Save the data the user enters into the form
- [x] Send a new GET request with the new parameters
- [x] Display the filtered search results
