### ISSUE TITLE
User can view an event result

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/final-project#4]
## 💰 Motivation

A result of the property the user selected with more details.

## 📐 Plan

Load the event with the time, date, description, and price range

## Mobile
<img width="194" alt="Screen Shot 2021-04-15 at 3 14 06 PM" src="https://user-images.githubusercontent.com/52344883/114944901-48499280-9dfd-11eb-8599-1806f662cec4.png">

## Desktop
<img width="599" alt="Screen Shot 2021-04-15 at 3 13 43 PM" src="https://user-images.githubusercontent.com/52344883/114944912-4bdd1980-9dfd-11eb-924d-25c70f512197.png">

## ✅ Task List
- [x] Add anchor tags to all rendered search results to a path with an ID parameter.
- [x] Add the hash-routing functionality to the app.jsx to render an individual search result page.
- [x] Export a default class from the individual search result page that renders the image, name, time, date, address, seatmap, and button that links to the ticketmaster website for ticket purchase
- [x] Add a back button that displays search results
